In [2]:
import numpy as np
import pprint
import scipy.linalg

In [150]:
A = np.matrix([[11,-8],[-8,-1]])

S = np.matrix([[-2,1],[1,2]])

print(np.linalg.inv(S)*A*S)

print(np.linalg.inv(S))

[[ 15.   0.]
 [  0.  -5.]]
[[-0.4  0.2]
 [ 0.2  0.4]]


# Exercicio computacional 1

In [18]:
A = np.matrix([[0,0,1],[1,0,1],[0,1,1],[1,1,1],[3,2,1]])

print(A)

b = np.matrix([[0],[3],[2],[4],[6]])

print(b)

pseudo_inversa = np.linalg.inv(np.transpose(A)*A)

print (pseudo_inversa)

x = pseudo_inversa*np.transpose(A)*b

print(x)



[[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [3 2 1]]
[[0]
 [3]
 [2]
 [4]
 [6]]
[[ 0.35897436 -0.38461538 -0.05128205]
 [-0.38461538  0.76923077 -0.23076923]
 [-0.05128205 -0.23076923  0.43589744]]
[[ 1.28205128]
 [ 0.76923077]
 [ 1.1025641 ]]


# Exercicio computacional 2

In [13]:
identidade = [[1,0],[0,1]]

A = np.matrix([[2.0/3, 1.0/3],[1.0/4,3.0/4]])

print(A)

autovalores, autovetores = (np.linalg.eig(A))

print("Autovetores: \n", autovetores)

D = autovalores*identidade

print("Autovalores: \n",D)



print("A convergencia da negociação ocorrerá para: \n", 
       (np.linalg.inv(autovetores.transpose())*(D**1000)*autovetores.transpose()).transpose())

#print(np.linalg.inv(autovetores.transpose())*D*(autovetores.transpose()))

#print((np.linalg.inv(autovetores)*(A)*autovetores))

[[ 0.66666667  0.33333333]
 [ 0.25        0.75      ]]
Autovetores: 
 [[-0.8        -0.70710678]
 [ 0.6        -0.70710678]]
Autovalores: 
 [[ 0.41666667  0.        ]
 [ 0.          1.        ]]
A convergencia da negociação ocorrerá para: 
 [[ 0.42857143  0.57142857]
 [ 0.42857143  0.57142857]]
[[ 0.66666667  0.25      ]
 [ 0.33333333  0.75      ]]
[[ 0.41666667  0.        ]
 [ 0.          1.        ]]


# Exercicio computacional 3

a) Dada uma matriz M estocastica qualquer, a soma das colunas é igual a 1. 1 sempre é um autovalor dela. Prova:
 
Fazemos primeiro A = (M - I*1)

Nessa A, somamos todas as linhas na primeira linha, o que resulta em uma primera linha = 0 (já que a soma de todas as colunas é 1 e adicionamos -1 do autovalor em todas elas). Essa operação não altera o det(A).

Como a primeira linha é = 0, temos que det(A) = 0. Logo, 1 é autovalor

In [57]:
M = np.matrix([[0.5, 0.3, 0.1],
               [0.3, 0.4, 0.3], 
               [0.2, 0.3, 0.6]]) 

estado_inicial = np.matrix([[0],[0],[1]])

k2 = M*M*estado_inicial

print("A resposta do item b) é: \n", k2)

autovalores, autovetores = np.linalg.eig(M)

print("Autovalores: \n", autovalores)

print("Autovetores: \n", autovetores)

print("O valor de estabilidade da matrix estocastica será o autovetor correspondente ao autovalor 1, ou seja: \n",
     autovetores.transpose()[0].transpose())


print("Podemos checar se é verdade multiplicando ela pela M e temos: \n", M*autovetores.transpose()[0].transpose())



#print(autovetores[0][0]+autovetores[1][0]+autovetores[2][0])

A resposta do item b) é: 
 [[ 0.2 ]
 [ 0.33]
 [ 0.47]]
Autovalores: 
 [ 1.   0.4  0.1]
Autovetores: 
 [[ -4.76731295e-01  -7.07106781e-01   5.34522484e-01]
 [ -5.72077554e-01   1.78763616e-16  -8.01783726e-01]
 [ -6.67423812e-01   7.07106781e-01   2.67261242e-01]]
O valor de estabilidade da matrix estocastica será o autovetor correspondente ao autovalor 1, ou seja: 
 [[-0.47673129]
 [-0.57207755]
 [-0.66742381]]
Podemos checar se é verdade multiplicando ela pela M e temos: 
 [[-0.47673129]
 [-0.57207755]
 [-0.66742381]]


# Exercicio computacional 4

In [145]:
A = np.matrix([[2,0,2/3,0,2/5,0],
               [0,2/3,0,2/5,0,2/7],
               [2/3,0,2/5,0,2/7,0],
               [0,2/5,0,2/7,0,2/9],
               [2/5,0,2/7,0,2/9,0],
               [0,2/7,0,2/9,0,2/11]])

print("A Matriz é: \n", A)

autovalores, V = (np.linalg.eig(A))

V = V.transpose()

print("Autovetores: \n", V)

D = autovalores*np.identity(6)

print("Autovalores: \n",D)

U = V*(np.linalg.inv(scipy.linalg.sqrtm(D)))

print("U: \n", U)

Q, R = np.linalg.qr(A)

#print(A - np.linalg.inv(V)*D*V)

print("Q: \n", Q)
print("R: \n", R)


A Matriz é: 
 [[ 2.          0.          0.66666667  0.          0.4         0.        ]
 [ 0.          0.66666667  0.          0.4         0.          0.28571429]
 [ 0.66666667  0.          0.4         0.          0.28571429  0.        ]
 [ 0.          0.4         0.          0.28571429  0.          0.22222222]
 [ 0.4         0.          0.28571429  0.          0.22222222  0.        ]
 [ 0.          0.28571429  0.          0.22222222  0.          0.18181818]]
Autovetores: 
 [[  9.13034434e-01   1.95653914e-17   3.44611116e-01   4.23457206e-18
    2.18200140e-01   3.16528898e-18]
 [  4.01386061e-01  -5.32095031e-17  -6.64019450e-01   1.38247269e-16
   -6.30846574e-01   1.03338341e-16]
 [  7.25076050e-02   5.19602498e-16  -6.63567139e-01  -5.11673774e-16
    7.44594721e-01  -3.82466064e-16]
 [ -1.03916076e-16   7.75962049e-01   2.58608435e-16   5.05232317e-01
   -1.92906554e-16   3.77654875e-01]
 [ -6.74560301e-17   6.07869167e-01   6.83508407e-16  -4.39050919e-01
   -8.48794977e-16  -6